import { Platform, Dimensions, StyleSheet } from "react-native";

import { FontFamily } from "../../assets/fonts";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  containerDark: {
    flex: 1,
    // backgroundColor: "#0D0B12",
  },
  logo: {
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    // marginBottom: "20%",
    // flex: 1,/
  },
  image: {
    flex: 1,
    justifyContent: "center",
  },
  titleText: {
    fontStyle: "normal",
    fontFamily: FontFamily.InterRegular,
    fontSize: 22,
    textAlign: "center",
    letterSpacing: -0.05,
    lineHeight: 41,
    color: "#ffffff",
  },
  headerText: {
    fontStyle: "normal",
    fontFamily: FontFamily.InterExtraBold,
    fontSize: 22,
    textAlign: "center",
    letterSpacing: -0.05,
    lineHeight: 41,
    color: "#ffffff",
  },
  subHeaderText: {
    fontFamily: FontFamily.InterRegular,
    fontSize: 14,
    textAlign: "center",
    lineHeight: 22,
    color: "#444444",
    fontStyle: "normal",
  },
  appleSignInButton: {
    // width:  Dimensions.get('screen').width-100,
    height: 61,
    flexDirection: "row",
    alignSelf: "center",
    marginVertical: 6,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#252525",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.37,
    shadowRadius: 7.49,
    elevation: 12,
  },
  signinBtn: {
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    alignSelf: "center",
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 4,
    height: 50,
    marginBottom: 15,
  },
  btnGoogleIcon: { height: 28, width: 24 },
  btnGoogleText: {
    marginHorizontal: 2,
    fontFamily: FontFamily.InterRegular,
    fontSize: 18,
    lineHeight: 21,
    color: "#000",
  },
  btnIcon: { height: 28, width: 23.13, marginRight: 10, resizeMode: "contain" },
  // googlebtnIcon: { height: 52, width: 52, resizeMode: "contain" },
  btnText: {
    // marginHorizontal: 15,
    fontFamily: FontFamily.InterRegular,
    fontSize: 20,
    color: "#1d1d1d",
  },
  bottomLinks: {
    bottom: 0,
    alignSelf: "center",
    width: Dimensions.get("screen").width - 100,
  },
  linktext: {
    fontStyle: "normal",
    fontFamily: FontFamily.InterRegular,
    fontSize: 14,
    textAlign: "center",
    color: "#fff",
    left: 15,
  },
  primaryText: {
    fontStyle: "normal",
    fontFamily: FontFamily.InterSemiBold,
    fontSize: 14,
    color: "#007AFF",
  },
  inputView: {
    borderRadius: 5,
    borderWidth: 2,
    borderColor: "#fff",
    backgroundColor: "#fff",
    alignSelf: "center",
    justifyContent: "center",
    // height: 40,
    width: "100%",
    // shadowColor: "#c4c4c4",
    // shadowOffset: {
    //   width: 1,
    //   height: 1,
    // },
    // shadowOpacity: 0.5,
    // shadowRadius: 10,
    // elevation: 4,
    padding: 10,
  },
  button: {
    borderWidth: 2,
    borderColor: "#007AFF",
    backgroundColor: "#007AFF",
    alignSelf: "center",
    justifyContent: "center",
    height: 40,
    paddingHorizontal: 35,
    borderRadius: 10,
    // width: "75%",
    // shadowColor: "#c4c4c4",
    // shadowOffset: {
    //   width: 0.1,
    //   height: 0.1,
    // },

    flexDirection: "row",
    // shadowOpacity: 0.5,
    // shadowRadius: 10,
    // elevation: 4,
    padding: 10,
    marginTop: "5%",
  },
  inputView1: {
    borderRadius: 5,
    borderWidth: 2,
    borderColor: "#fff",
    backgroundColor: "#fff",
    alignSelf: "center",
    justifyContent: "center",
    height: "10%",
    width: "40%",
    shadowColor: "#c4c4c4",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 4,
    padding: 10,
  },
  buttonText: {
    justifyContent: "center",
    alignSelf: "center",
    fontStyle: "normal",
    fontFamily: FontFamily.InterBold,
    fontSize: 14,
    textAlign: "center",
    letterSpacing: 0.2,
    // marginHorizontal: "5%",
    color: "#fff",
  },
  errorText: {
    fontSize: 12,
    color: "red",
    // marginLeft: "13%",
    marginVertical: Platform.OS === "web" ? 2 : 5,
  },
});
